version: "3.7"
services:
  golang.dev.local:
    container_name: golang.dev.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/home/devuser/workspace:cached
      - ./envs:/home/devuser/envs:cached
    ports:
      - "3000:3000"
    privileged: true
    tty: true
