version: "3.7"
services:
  rust1.dev.local:
    container_name: rust1.dev.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/home/devuser/workspace:cached
      - ./envs:/home/devuser/envs:cached
    privileged: true
    tty: true
